services:  
  api:
    git_url: http://github.com/cloud66-samples/go_api_habitus.git
    git_branch: master
    use_habitus: true
    use_habitus_step: runtime
    ports:
      - container: 8080
        http: 80
        https: 443
databases:
  - mongodb
