services:  
  api:
    git_url: http://github.com/kamerblauwlicht/microbadger_habitus_go_example.git
    git_branch: master
    use_habitus: true
    use_habitus_step: runtime
    ports:
      - container: 8080
        http: 80
        https: 443
